### ISSUE TITLE
Blade height in inches? Area in sq. ft?

### ISSUE THREAD

**Issue by nappyjim** [mikey0000/Mammotion-HA#50] opened 2024-08-03 03:01 UTC
### The problem

Maybe not a problem, just more a feature request for us in the US.  There a way to get the blade height to be in inches?  Area in sq. ft instead of sq. m. 

Thank you.  Great work.

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

unsure

### What version of Home Assistant Core are you running?

2024.7.4

**Comment by mikey0000** [comment] 2024-08-03 04:49
Home assistant is supposed to do the conversion so will investigate

**Comment by mikey0000** [comment] 2024-08-09 07:41
Have all of those for you except square ft as for some reason ha doesn't have the conversion (I'll do this for the next release)

**Comment by mikey0000** [comment] 2024-08-10 05:45
Just need confirmation this is now working for you? I still need to do square ft

**Comment by mikey0000** [comment] 2024-08-13 22:10
Done, except Area, HA doesn't support sq. ft. Have raised it in architecture. Closing for now as not a bug in this integration but rather an issue with HA itself. Raise some noise in architecture for sq. ft I've got an open discussion.

**Closed by mikey0000** 2024-08-13 22:10 UTC
