### ISSUE TITLE
Yuka blade height wrong when docked

### ISSUE THREAD

**Issue by TTLucian** [mikey0000/Mammotion-HA#48] opened 2024-07-22 17:57 UTC
### The problem

Integration always shows 50mm blade height when the robot is docked. The set blade height is correct when the robot is mowing. 

### What Mammotion mower are you using?

Yuka

### What version of the Mammotion intergration are you using?

0.0.4

### What version of Home Assistant Core are you running?

core-2024.7.3

**Comment by TTLucian** [comment] 2024-07-22 19:20
I think it does. It reports the correct value when it's mowing but not when it's docked.

**Comment by romeoechovictor** [comment] 2024-07-22 19:23
Doesn't the Luba always reset it's blade height to 50mm when docking. So you see 50mm when docked and Xmm when mowing.  Not sure about Yuka, but this sounds normal for Luba, ie not a bug.

**Comment by TTLucian** [comment] 2024-07-22 19:28
I understand. Don't know about Luba. I own a Yuka. I've changed the blade height several times. It always reports the correct value when mowing but when docked, it reports 50 mm. I don't know if it's a bug in the firmware or the in the ha integration.

**Comment by romeoechovictor** [comment] 2024-07-22 19:29
When your Yuka docks does it reset it's blade height back to 50mm like it does on my Luba? Maybe you can check in the app when it's going back to the dock

**Comment by romeoechovictor** [comment] 2024-07-22 19:32
Ah ok. I understand now. Strange so that it reports a different value.   I guess if docked then don't report any height to hass?

**Comment by TTLucian** [comment] 2024-07-22 19:34
The app doesn't show the blade height setting. But the integration does and it is correct when the robot is mowing. If I set it to 70, the ha integration actually reports 70, but only when it's mowing. It reports 50 mm when docked. So I'm thinking that the robot actually does have a blade height sensor. I'll test this further and report back.

**Comment by TTLucian** [comment] 2024-07-22 19:48
I'll test it tomorrow and report back.

**Comment by TTLucian** [comment] 2024-07-23 18:12
It would seem that it reports 50 when docked and 60 when mowing regardless of the actual setting. In my initial test I had the blade height set at 60 so I presumed that it reports correctly. It was just a coincidence. I don't know if it actually has a blade height sensor.

**Comment by dodavies** [comment] 2024-07-29 17:35
just ordered on says it does 20mm, I really hope it does !

**Comment by mikey0000** [comment] 2024-08-13 22:11
Closing as the blade height entity is no longer displayed on Yuka devices.

**Comment by TTLucian** [comment] 2024-08-14 18:25
Issue still present on v0.0.22. Did I miss something? 
![Screenshot_2024-08-14-21-24-41-80_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/37ffb445-9251-43a3-a0e8-fad68905d2f8)

**Comment by mikey0000** [comment] 2024-08-14 19:34
I'll take a look

**Comment by mikey0000** [comment] 2024-08-21 00:09
We need to fix up the device identification logic. We'll fix it when we get to it :)

**Closed** 2024-09-13 05:18 UTC
Labels: bug
