### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by ranug9** [mikey0000/Mammotion-HA#191] opened 2024-10-25 15:10 UTC
### The problem

Installed the Mammotion Integration, created an extra account on a different phone, shared the luba and the RTK Station.  Then I tried to login with this new account into the integration, this failed with "unknown error". Updated to version 0.1.79.
Here some logs:

Logger: pymammotion.aliyun.cloud_gateway
Source: /usr/local/lib/python3.12/site-packages/pymammotion/aliyun/cloud_gateway.py:525
First occurred: 16:48:41 (2 occurrences)
Last logged: 16:52:29

{'code': 2401, 'id': '607e4da4-1235-4eef-a210-68d8d42801d4', 'localizedMsg': 'refreshToken invalid!!', 'message': 'refreshToken invalid!!'}
{'code': 2401, 'id': '47de3364-31e4-4fed-b1ab-b6a720fa7b11', 'localizedMsg': 'refreshToken invalid!!', 'message': 'refreshToken invalid!!'}

and this one:

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 16:48:43 (2 occurrences)
Last logged: 16:52:31

Error setting up entry Luba-VS2GR5E7 for mammotion
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/__init__.py", line 61, in async_setup_entry
    await mammotion_coordinator.async_setup()
  File "/config/custom_components/mammotion/coordinator.py", line 259, in async_setup
    await self.async_login()
  File "/config/custom_components/mammotion/coordinator.py", line 118, in async_login
    await self.manager.login_and_initiate_cloud(account, password, True)
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 182, in login_and_initiate_cloud
    cloud_client = await self.login(account, password)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 235, in login
    mammotion_http = await connect_http(account, password)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/http/http.py", line 85, in connect_http
    return MammotionHTTP(login_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/http/http.py", line 19, in __init__
    self.login_info = LoginResponseData.from_dict(response.data) if response.data else None
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 37, in __mashumaro_from_dict__
mashumaro.exceptions.MissingField: Field "jti" of type str is missing in LoginResponseData instance

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.79

### What version of Home Assistant Core are you running?

latest

**Comment by mikey0000** [comment] 2024-10-25 20:00
Duplicate of #189 fix coming shortly

**Closed by mikey0000** 2024-10-25 20:00 UTC
