### ISSUE TITLE
Luba 2 does not respont to commands

### ISSUE THREAD

**Issue by JanKruemmel** [mikey0000/Mammotion-HA#28] opened 2024-07-09 06:00 UTC
Hello, first of all very nice that the integration is available and thanks for the time you are spending in dev.

My mower is connected and I can see all values like battery, status and so far.
But I can not statt / stop mowing. The mower does not respond to commends.

Any Suggestions?

All the best

Jan

**Comment by mikey0000** [comment] 2024-07-09 06:18
Yeah we don't have Luba 2s so don't know why. I'll try and investigate.

**Comment by TTLucian** [comment] 2024-07-12 20:18
Same problem here with Yuka robot.

**Comment by TTLucian** [comment] 2024-07-16 22:13
Latest update doesn't fix the problem.

**Comment by mikey0000** [comment] 2024-07-17 00:15
We are aware and are working on it, it requires pull all the map data off to issue the correct command, hold tight

**Comment by mikey0000** [comment] 2024-08-13 22:12
Closing as it is now resolved.

**Closed by mikey0000** 2024-08-13 22:12 UTC
Labels: Luba 2

**Comment by TTLucian** [comment] 2024-08-14 18:22
The issue is still present on v0.0.22 for Yuka. Start command does nothing. Sync maps throws an error. All configuration switches and sliders are throwing errors.

**Comment by TTLucian** [comment] 2024-08-20 18:01
Also, after start mowing in HA, Mammotion app shows error "Mowing area selection is abnormal (1415)". Am I missing something?
